// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/analizadorfinalmad/Lexer.flex

package analizadorfinalmad;
import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\11\1\10\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\11\25\1\10\1\26\1\27\1\30\1\31\2\10\4\32"+
    "\1\33\3\32\1\34\21\32\1\10\1\35\2\10\1\32"+
    "\1\10\1\36\1\37\1\40\1\41\1\42\1\43\1\32"+
    "\1\44\1\45\1\46\1\32\1\47\1\50\1\51\1\52"+
    "\1\53\1\32\1\54\1\55\1\56\1\57\1\60\1\32"+
    "\1\61\2\32\1\62\1\63\1\64\7\0\1\3\71\0"+
    "\1\10\1\0\1\65\7\0\1\65\3\0\1\65\3\0"+
    "\1\65\1\0\1\65\6\0\1\65\1\0\1\65\4\0"+
    "\1\65\7\0\1\65\3\0\1\65\3\0\1\65\1\0"+
    "\1\65\6\0\1\65\1\0\1\65\u012b\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\2\15"+
    "\1\16\1\17\1\20\1\21\13\22\1\23\1\1\1\24"+
    "\1\25\1\0\1\1\1\26\1\27\1\0\1\1\1\0"+
    "\2\1\1\30\1\31\1\0\1\2\1\0\1\1\1\0"+
    "\2\1\1\0\1\32\1\33\1\34\7\22\1\35\2\22"+
    "\1\36\2\26\1\1\1\0\1\37\1\0\2\1\1\37"+
    "\1\0\1\1\2\0\2\15\1\1\2\0\1\15\1\0"+
    "\1\1\1\15\1\1\2\0\10\22\1\0\1\1\1\0"+
    "\1\2\1\0\1\15\1\1\2\15\1\40\12\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[124];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\70\0\160\0\250\0\340\0\70\0\u0118"+
    "\0\u0150\0\70\0\70\0\70\0\u0188\0\70\0\u01c0\0\70"+
    "\0\u01f8\0\u0230\0\u0268\0\70\0\u02a0\0\u02d8\0\u0310\0\u0348"+
    "\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0\0\u0508"+
    "\0\u0540\0\u0578\0\70\0\u05b0\0\70\0\70\0\u05e8\0\u0620"+
    "\0\u0658\0\70\0\u0690\0\u06c8\0\u0700\0\u0738\0\u0770\0\70"+
    "\0\70\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888\0\u08c0\0\u08f8"+
    "\0\u0930\0\70\0\70\0\70\0\u0968\0\u09a0\0\u09d8\0\u0a10"+
    "\0\u0a48\0\u0a80\0\u0ab8\0\u0348\0\u0af0\0\u0b28\0\70\0\70"+
    "\0\u0b60\0\u0b98\0\u0bd0\0\70\0\u0c08\0\u0c40\0\u0c78\0\u0cb0"+
    "\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e00\0\u0e38"+
    "\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f18\0\u0f50\0\u0f88\0\u0fc0"+
    "\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180"+
    "\0\u11b8\0\u11f0\0\u1228\0\u0d58\0\u1260\0\u1298\0\u12d0\0\u12d0"+
    "\0\u1308\0\u0348\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458"+
    "\0\u1490\0\u14c8\0\u1500\0\u1538";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\2"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\2\30\1\31\1\2\1\30\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\2\30\1\40\1\41\2\30\1\42"+
    "\1\30\1\43\1\44\1\30\1\45\1\30\1\46\1\47"+
    "\1\50\1\30\70\0\1\3\113\0\1\51\35\0\1\52"+
    "\1\53\3\52\2\53\1\54\3\53\1\52\21\53\1\52"+
    "\27\53\1\52\12\0\1\55\53\0\2\56\1\0\10\56"+
    "\1\57\3\56\1\60\1\56\1\60\2\56\2\61\4\56"+
    "\3\62\1\0\24\62\4\56\21\0\1\63\3\0\1\23"+
    "\56\0\1\64\4\0\1\65\42\0\2\66\4\0\24\66"+
    "\3\67\1\66\24\67\3\66\1\67\2\70\4\0\16\70"+
    "\2\23\4\70\1\71\1\72\1\71\1\70\4\71\1\72"+
    "\17\71\1\70\1\73\1\70\1\71\30\0\1\74\65\0"+
    "\1\75\65\0\1\76\61\0\2\30\4\0\3\30\1\0"+
    "\24\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\13\30\1\77\10\30\3\0\1\30\24\0\2\30\4\0"+
    "\3\30\1\0\14\30\1\100\7\30\3\0\1\30\24\0"+
    "\2\30\4\0\3\30\1\0\6\30\1\101\15\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\1\30\1\102"+
    "\22\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\13\30\1\103\10\30\3\0\1\30\24\0\2\30\4\0"+
    "\3\30\1\0\1\104\10\30\1\105\12\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\1\106\23\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\4\30\1\107"+
    "\4\30\1\110\12\30\3\0\1\30\24\0\2\30\4\0"+
    "\3\30\1\0\4\30\1\111\2\30\1\112\14\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\1\113\23\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\7\30"+
    "\1\114\14\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\4\30\1\115\17\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\4\30\1\116\17\30\3\0\1\30"+
    "\63\0\1\117\2\0\7\52\1\120\57\52\1\53\3\52"+
    "\2\53\1\121\3\53\1\52\21\53\1\52\27\53\1\52"+
    "\1\0\1\122\3\0\2\122\1\54\3\122\1\0\21\122"+
    "\1\0\27\122\1\0\2\123\1\0\10\123\1\124\21\123"+
    "\1\0\30\123\13\0\1\57\3\0\1\125\1\0\1\125"+
    "\2\0\2\126\4\0\3\127\1\0\24\127\4\0\2\123"+
    "\1\0\10\123\1\124\10\123\2\61\7\123\1\0\32\123"+
    "\1\0\10\123\1\130\3\123\1\131\1\123\1\131\2\123"+
    "\2\61\4\123\3\132\1\0\24\132\6\123\1\0\10\123"+
    "\1\130\3\123\1\131\1\123\1\131\2\123\2\132\4\123"+
    "\3\132\1\0\24\132\4\123\16\133\1\134\47\133\2\65"+
    "\1\3\2\65\1\4\60\65\24\0\1\135\65\0\1\136"+
    "\1\137\4\0\3\137\1\0\24\137\3\0\1\137\16\0"+
    "\1\140\5\0\1\141\1\142\5\0\1\143\6\0\1\143"+
    "\20\0\1\143\20\0\1\140\5\0\1\144\1\145\4\0"+
    "\1\137\1\146\1\137\1\0\4\137\1\146\17\137\1\0"+
    "\1\143\1\0\1\137\16\0\1\140\1\147\1\0\1\147"+
    "\2\0\1\144\1\145\4\0\1\137\1\146\1\137\1\0"+
    "\4\137\1\146\17\137\1\0\1\150\1\0\1\137\16\0"+
    "\1\140\1\147\1\0\1\147\2\0\1\141\1\142\5\0"+
    "\1\143\6\0\1\143\20\0\1\150\26\0\2\30\4\0"+
    "\3\30\1\0\7\30\1\151\14\30\3\0\1\30\24\0"+
    "\2\30\4\0\3\30\1\0\14\30\1\102\7\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\1\152\23\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\11\30"+
    "\1\153\12\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\20\30\1\153\3\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\11\30\1\154\12\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\14\30\1\103\7\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\2\30"+
    "\1\155\21\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\2\30\1\156\21\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\1\157\23\30\3\0\1\30\24\0"+
    "\2\30\4\0\3\30\1\0\13\30\1\160\4\30\1\161"+
    "\3\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\4\30\1\162\17\30\3\0\1\30\24\0\2\30\4\0"+
    "\3\30\1\0\16\30\1\163\5\30\3\0\1\30\24\0"+
    "\2\30\4\0\3\30\1\0\13\30\1\164\10\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\23\30\1\165"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\16\30"+
    "\1\166\5\30\3\0\1\30\7\0\1\121\57\0\1\122"+
    "\3\0\2\122\1\121\3\122\1\0\21\122\1\0\27\122"+
    "\1\0\2\123\1\0\10\123\1\2\21\123\1\0\30\123"+
    "\24\0\2\126\53\0\1\130\3\0\1\167\1\0\1\167"+
    "\2\0\2\126\4\0\3\170\1\0\24\170\17\0\1\130"+
    "\3\0\1\167\1\0\1\167\2\0\2\170\4\0\3\170"+
    "\1\0\24\170\17\0\1\130\52\0\2\123\1\0\10\123"+
    "\1\2\10\123\2\132\7\123\1\0\32\123\1\0\10\123"+
    "\1\2\3\123\1\131\1\123\1\131\2\123\2\132\4\123"+
    "\3\132\1\0\24\132\4\123\16\133\1\171\65\133\1\171"+
    "\4\133\1\172\42\133\32\0\3\137\1\0\24\137\3\0"+
    "\1\137\24\0\2\137\4\0\3\137\1\0\24\137\3\0"+
    "\1\137\33\0\1\143\6\0\1\143\20\0\1\143\26\0"+
    "\1\173\1\174\5\0\1\143\6\0\1\143\20\0\1\143"+
    "\26\0\1\173\1\174\4\0\1\137\1\146\1\137\1\0"+
    "\4\137\1\146\17\137\1\0\1\143\1\0\1\137\17\0"+
    "\1\147\1\0\1\147\41\0\1\147\26\0\1\175\1\176"+
    "\4\0\1\137\1\146\1\137\1\0\4\137\1\146\17\137"+
    "\1\0\1\143\1\0\1\137\17\0\1\147\1\0\1\147"+
    "\2\0\2\137\4\0\3\137\1\0\24\137\1\0\1\147"+
    "\1\0\1\137\25\0\1\177\57\0\1\147\1\0\1\147"+
    "\3\0\1\177\35\0\1\147\26\0\2\30\4\0\3\30"+
    "\1\0\2\30\1\200\21\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\16\30\1\153\5\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\17\30\1\164\4\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\4\30"+
    "\1\201\17\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\20\30\1\202\3\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\12\30\1\203\11\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\17\30\1\204\4\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\14\30"+
    "\1\205\7\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\13\30\1\206\10\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\1\207\23\30\3\0\1\30\24\0"+
    "\2\30\4\0\3\30\1\0\14\30\1\207\7\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\20\30\1\210"+
    "\3\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\3\30\1\211\20\30\3\0\1\30\24\0\2\170\57\0"+
    "\1\167\1\0\1\167\2\0\2\170\4\0\3\170\1\0"+
    "\24\170\4\0\16\133\1\171\4\133\1\3\42\133\24\0"+
    "\1\173\1\174\64\0\1\173\1\174\4\0\3\137\1\0"+
    "\24\137\3\0\1\137\24\0\1\175\1\176\4\0\3\137"+
    "\1\0\24\137\3\0\1\137\24\0\2\177\4\0\3\137"+
    "\1\0\24\137\3\0\1\137\24\0\2\30\4\0\3\30"+
    "\1\0\7\30\1\164\14\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\16\30\1\207\5\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\21\30\1\113\2\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\1\201"+
    "\23\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\1\212\23\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\3\30\1\164\20\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\20\30\1\213\3\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\14\30\1\153\7\30"+
    "\3\0\1\30\24\0\2\30\4\0\3\30\1\0\1\214"+
    "\23\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\10\30\1\215\13\30\3\0\1\30\24\0\2\30\4\0"+
    "\3\30\1\0\16\30\1\216\5\30\3\0\1\30\24\0"+
    "\2\30\4\0\3\30\1\0\3\30\1\217\20\30\3\0"+
    "\1\30\24\0\2\30\4\0\3\30\1\0\4\30\1\207"+
    "\17\30\3\0\1\30\24\0\2\30\4\0\3\30\1\0"+
    "\1\220\23\30\3\0\1\30\24\0\2\30\4\0\3\30"+
    "\1\0\4\30\1\221\17\30\3\0\1\30\24\0\2\30"+
    "\4\0\3\30\1\0\17\30\1\207\4\30\3\0\1\30"+
    "\24\0\2\30\4\0\3\30\1\0\16\30\1\164\5\30"+
    "\3\0\1\30";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6426];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\1\11\2\1\5\11\1\1\1\11"+
    "\3\1\1\11\21\1\1\11\1\1\2\11\1\0\2\1"+
    "\1\11\1\0\1\1\1\0\2\1\1\11\1\0\1\1"+
    "\1\0\1\1\1\0\2\1\1\0\3\11\20\1\2\11"+
    "\2\1\1\0\1\11\1\0\3\1\1\0\1\1\2\0"+
    "\3\1\2\0\1\1\1\0\3\1\2\0\16\1\1\0"+
    "\1\1\1\0\1\1\1\0\26\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[145];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 33: break;
          case 3:
            { return token(yytext(), "?", yyline, yycolumn);
            }
            // fall through
          case 34: break;
          case 4:
            { return token(yytext(), "$", yyline, yycolumn);
            }
            // fall through
          case 35: break;
          case 5:
            { return token(yytext(), "(", yyline, yycolumn);
            }
            // fall through
          case 36: break;
          case 6:
            { return token(yytext(), ")", yyline, yycolumn);
            }
            // fall through
          case 37: break;
          case 7:
            { return token(yytext(), "*", yyline, yycolumn);
            }
            // fall through
          case 38: break;
          case 8:
            { return token(yytext(), "+", yyline, yycolumn);
            }
            // fall through
          case 39: break;
          case 9:
            { return token(yytext(), ",", yyline, yycolumn);
            }
            // fall through
          case 40: break;
          case 10:
            { return token(yytext(), "-", yyline, yycolumn);
            }
            // fall through
          case 41: break;
          case 11:
            { return token(yytext(), ".", yyline, yycolumn);
            }
            // fall through
          case 42: break;
          case 12:
            { return token(yytext(), "/", yyline, yycolumn);
            }
            // fall through
          case 43: break;
          case 13:
            { return token(yytext(), "num", yyline, yycolumn);
            }
            // fall through
          case 44: break;
          case 14:
            { return token(yytext(), ";", yyline, yycolumn);
            }
            // fall through
          case 45: break;
          case 15:
            { return token(yytext(), "<", yyline, yycolumn);
            }
            // fall through
          case 46: break;
          case 16:
            { return token(yytext(), "=", yyline, yycolumn);
            }
            // fall through
          case 47: break;
          case 17:
            { return token(yytext(), ">", yyline, yycolumn);
            }
            // fall through
          case 48: break;
          case 18:
            { return token(yytext(), "id", yyline, yycolumn);
            }
            // fall through
          case 49: break;
          case 19:
            { return token(yytext(), "{", yyline, yycolumn);
            }
            // fall through
          case 50: break;
          case 20:
            { return token(yytext(), "}", yyline, yycolumn);
            }
            // fall through
          case 51: break;
          case 21:
            { return token(yytext(), "!=", yyline, yycolumn);
            }
            // fall through
          case 52: break;
          case 22:
            { return token(yytext(), "litCad", yyline, yycolumn);
            }
            // fall through
          case 53: break;
          case 23:
            { return token(yytext(), "--", yyline, yycolumn);
            }
            // fall through
          case 54: break;
          case 24:
            { return token(yytext(), "--", yyline, yycolumn);
            }
            // fall through
          case 55: break;
          case 25:
            { return token(yytext(), "<=", yyline, yycolumn);
            }
            // fall through
          case 56: break;
          case 26:
            { return token(yytext(), "#", yyline, yycolumn);
            }
            // fall through
          case 57: break;
          case 27:
            { return token(yytext(), ">=", yyline, yycolumn);
            }
            // fall through
          case 58: break;
          case 28:
            { return token(yytext(), "pReservada", yyline, yycolumn);
            }
            // fall through
          case 59: break;
          case 29:
            { return token(yytext(), "%", yyline, yycolumn);
            }
            // fall through
          case 60: break;
          case 30:
            { return token(yytext(), "litCar", yyline, yycolumn);
            }
            // fall through
          case 61: break;
          case 31:
            { return token(yytext(), "tipoDa", yyline, yycolumn);
            }
            // fall through
          case 62: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
